---
name: bundle
on:
  push:
    tags:
      - '*'

jobs:
  bundle:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - 'windows-latest'
        - 'ubuntu-latest'
        - 'macos-latest'

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - run: pip install poetry
    - run: poetry install
    - run: poetry run pip install pyinstaller
    - run: poetry run pyinstaller --name scim2 --onefile scim2_cli/__init__.py
    - run: ./dist/scim2
    - uses: actions/upload-artifact@v4
      if: ${{ matrix.os != 'windows-latest' }}
      with:
        name: scim2-${{ github.ref_name }}-${{ matrix.os }}
        path: ./dist/scim2
        if-no-files-found: error
    - uses: actions/upload-artifact@v4
      if: ${{ matrix.os == 'windows-latest' }}
      with:
        name: scim2-${{ github.ref_name }}-${{ matrix.os }}
        path: ./dist/scim2.exe
        if-no-files-found: error

  release:
    needs: bundle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: scim2-${{ github.ref_name }}-*
          path: dist
      - uses: softprops/action-gh-release@v2
        with:
          files: dist/*
